In [2]:
import pandas as pd

In [3]:
train=pd.read_csv('train.csv', nrows=10);
test=pd.read_csv('test.csv', nrows=10);
samples=pd.read_csv('sample_submission.csv', nrows=10);

In [4]:
train.head()

   row_id       x       y  accuracy    time    place_id
0       0  0.7941  9.0809        54  470702  8523065625
1       1  5.9567  4.7968        13  186555  1757726713
2       2  8.3078  7.0407        74  322648  1137537235
3       3  7.3665  2.5165        65  704587  6567393236
4       4  4.0961  1.1307        31  472130  7440663949

In [5]:
test.head()

   row_id       x       y  accuracy    time
0       0  0.1675  1.3608       107  930883
1       1  7.3909  2.5301        35  893017
2       2  8.0978  2.3473        62  976933
3       3  0.9990  1.0591        62  907285
4       4  0.6670  9.7254        40  914399

In [6]:
samples.head()

   row_id                          place_id
0       0  3073560757 9004412889 5652080691
1       1  1652178628 4379515211 6612350960
2       2  4894407065 3920195083 7608574746
3       3  7272466660 2004687925 1455486822
4       4  4720452725 4967325204 4782917866

In [7]:
train=pd.read_csv('train.csv');
test=pd.read_csv('test.csv');
samples=pd.read_csv('sample_submission.csv');

In [8]:
print train.x.max(), train.x.min(), train.y.max(), train.y.min()

10.0 0.0 10.0 0.0

In [19]:
groups=train.place_id.value_counts()

In [22]:
groups.head()
type(groups)

pandas.core.series.Series

In [10]:
groupby=train.groupby('place_id')
groupby.head()

            row_id       x       y  accuracy    time    place_id
0                0  0.7941  9.0809        54  470702  8523065625
1                1  5.9567  4.7968        13  186555  1757726713
2                2  8.3078  7.0407        74  322648  1137537235
3                3  7.3665  2.5165        65  704587  6567393236
4                4  4.0961  1.1307        31  472130  7440663949
5                5  3.8099  1.9586        75  178065  6289802927
6                6  6.3336  4.3720        13  666829  9931249544
7                7  5.7409  6.7697        85  369002  5662813655
8                8  4.3114  6.9410         3  166384  8471780938
9                9  6.3414  0.0758        65  400060  1253803156
10              10  2.0173  4.8627         6   21353  8684462954
11              11  8.7101  2.9442        73  153493  2159916487
12              12  0.8829  1.3445        64  574488  7652380351
13              13  2.4336  8.0600        62  238054  8234363596
14              14  6.1550  1.9774         8  325411  2272949794
15              15  7.6219  9.6208        65  321519  4740742194
16              16  3.2494  3.2096        75  777982  2123587484
17              17  0.7084  8.9051        69  320633  8016758016
18              18  2.7256  1.0135        54    6249  8936085695
19              19  4.2683  1.8238        70  411437  2778700985
20              20  5.3298  6.3457        52  736113  4845908305
21              21  4.2830  3.1855        62  500479  3938338894
22              22  9.6349  1.2462       172  181701  9784464752
23              23  7.4492  8.9950        17  726403  1874355796
24              24  1.2837  7.5588         4  245292  9885174082
25              25  7.6423  6.7629        70  323935  4294512385
26              26  4.6375  3.4561        67  297623  7766380992
27              27  4.3794  7.2107       165  727097  2110807282
28              28  7.2382  4.3998        75   11929  9713229580
29              29  4.5083  1.8794         2  310734  6163271747
...            ...     ...     ...       ...     ...         ...
28657903  28657903  4.9450  6.7366         5  739176  7408197833
28668518  28668518  7.1178  4.0088        75  183223  4212392186
28670515  28670515  3.6021  6.2477        32  739252  3260584552
28672555  28672555  6.9622  8.3905        10  515258  1035424437
28710788  28710788  9.6844  0.1550       224  331999  6811634503
28737330  28737330  6.7019  2.3545        54  481762  5637447855
28765563  28765563  7.1126  0.7024         7  751468  1812955667
28777896  28777896  2.3967  4.9544        34  521535  3811332187
28786683  28786683  5.5072  9.5782         7  123748  9686221540
28793779  28793779  2.7086  8.6194       169  723740  5710315461
28795039  28795039  5.3886  9.0221        65  783642  6871091736
28806302  28806302  9.1548  9.3501        42  627337  9762494481
28807080  28807080  8.0323  5.7283        57  773128  3110194770
28816476  28816476  6.3791  3.3703        15  479741  7755652176
28821282  28821282  1.1315  9.8315        23  476624  9324708556
28837438  28837438  1.5100  3.7481        71  370813  8262263483
28840447  28840447  5.3652  0.5147        58  538685  1775519599
28876372  28876372  0.2554  3.6153         6  785641  1767379706
28880886  28880886  1.9683  7.9141        71  559763  8806200160
28908997  28908997  9.5200  2.2120        16   49957  4512767613
28911812  28911812  0.5235  0.6074       232  780588  4163351483
28926000  28926000  6.5550  3.9660        71  773388  7921226332
28950388  28950388  4.1023  1.5996        35  405568  3137310714
28954264  28954264  1.7077  9.7134        58  749003  6552589795
28974538  28974538  7.9350  4.7496         9  311674  6447932607
29012435  29012435  9.9455  6.3586        67  559121  7244010143
29069060  29069060  0.1853  7.8775        26  230694  8602349193
29076533  29076533  0.9602  2.3386        27  785348  3960259522
29102001  29102001  1.7152  2.1609        58  747221  6359057194
29117819  29117819  2.6425  8.6041        63  721476  5710315461

[540013 rows x 6 columns]

In [11]:
train.x.describe()

count    2.911802e+07
mean     4.999770e+00
std      2.857601e+00
min      0.000000e+00
25%      2.534700e+00
50%      5.009100e+00
75%      7.461400e+00
max      1.000000e+01
Name: x, dtype: float64

In [12]:
type(groupby)

pandas.core.groupby.DataFrameGroupBy

In [29]:
frequentPlaces=groupby.count().sort_values('time', ascending=False)

In [27]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
a=3
b=4
a
b

3

4

In [28]:
a
b

3

4